In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
my_data=np.loadtxt('ex1data2.txt',delimiter=',')
m=my_data.shape[0]

In [40]:
def normalize(X):
    n_col=X.shape[1]
    Xc=X.copy()
    for i in range(n_col):
        Xc[:,i]=(Xc[:,i]-Xc[:,i].mean())/Xc[:,i].std()
    return Xc
    

In [42]:
my_data_n=normalize(my_data)

In [47]:
X=np.c_[np.ones((m,1)),my_data_n[:,[0,1]]]

In [51]:
def compute_cost(X,theta):
    m=X.shape[0]
    res=np.dot(X,theta)-my_data_n[:,-1,np.newaxis]
    return (res**2).sum()/(2*m)

In [52]:
theta=np.array([0,0,0]).reshape((3,1))

In [114]:
def gradient_descent(X,y,theta,alpha,iterations):
    J=[]
    m=X.shape[0]
    for i in range(iterations):
        J.append(compute_cost(X,theta))
        tmp=np.dot(X,theta)-y
        for j in range(theta.shape[]):
            theta[j]=theta[j]-alpha/m*(tmp*X[:,j]).sum()
    return (J,theta)

In [125]:
alpha=0.005
theta=np.array([0,0,0],float).reshape((3,1))
iterations=2000
L=gradient_descent(X,my_data_n[:,-1,np.newaxis],theta,alpha,iterations)

In [126]:
L[1]

array([[ -8.24252014e-17],
       [  8.79037912e-01],
       [ -4.74508756e-02]])

In [131]:
A=np.linalg.pinv(np.dot(X.T,X))
np.dot(np.dot(A,X.T),y)

array([[  5.89805982e-17],
       [  8.84765988e-01],
       [ -5.31788197e-02]])

In [130]:
y

array([[ 0.48089023],
       [-0.08498338],
       [ 0.23109745],
       [-0.87639804],
       [ 1.61263744],
       [-0.32750064],
       [-0.20624201],
       [-1.1431751 ],
       [-1.03807621],
       [-0.791517  ],
       [-0.81173485],
       [ 0.05325146],
       [-0.08418307],
       [ 2.90606282],
       [-0.65085698],
       [ 0.88508566],
       [-0.32750064],
       [-1.1358915 ],
       [ 1.29007331],
       [ 2.09039644],
       [-0.70744435],
       [-0.69046814],
       [-0.78828343],
       [-0.65085698],
       [ 1.88749033],
       [-0.73169607],
       [ 1.00311072],
       [ 1.03948831],
       [ 1.08799176],
       [-0.32750064],
       [ 0.07669479],
       [-1.37840876],
       [-0.20624201],
       [ 1.93599378],
       [-0.44067536],
       [-0.73169607],
       [-0.89337424],
       [ 0.03708364],
       [ 1.686201  ],
       [-0.43178306],
       [ 0.22705549],
       [-0.08498338],
       [-0.21351753],
       [-0.33477616],
       [-1.29756968],
       [-0